Implemented prepare_release script for ci/cd pipeline

diff --git a/.ci/prepare_release b/.ci/prepare_release
--- a/.ci/prepare_release
+++ b/.ci/prepare_release
@@ -1,2 +1,32 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
+set -e
+
+if [ -z "$SOURCE_PATH" ]; then
+  export SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
+else
+  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
+fi
+
+function bump_version() {
+  local version="$(cat "${SOURCE_PATH}/VERSION")"
+  if [ -z "$version" ]
+  then
+    echo "Version not found"
+    exit 1
+  fi
+  # bump backend version
+  sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/g" "${SOURCE_PATH}/backend/package.json"
+  npm i --prefix "${SOURCE_PATH}/backend"
+  git add "${SOURCE_PATH}/backend/package.json"
+  git add "${SOURCE_PATH}/backend/package-lock.json"
+  # bump frontend version
+  sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/g" "${SOURCE_PATH}/frontend/package.json"
+  npm i --prefix "${SOURCE_PATH}/frontend"
+  git add "${SOURCE_PATH}/frontend/package.json"
+  git add "${SOURCE_PATH}/frontend/package-lock.json"
+  # commit changes
+  git commit -m "Update frontend and backend to version $version"
+}
+
+bump_version
