PR Feedback

diff --git a/.ci/verify b/.ci/verify
--- a/.ci/verify
+++ b/.ci/verify
@@ -1,6 +1,6 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
+# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
 #
 # SPDX-License-Identifier: Apache-2.0
 
@@ -17,27 +17,33 @@ else
   export MAIN_REPO_DIR="$(readlink -f ${MAIN_REPO_DIR})"
 fi
 
-pushd "${MAIN_REPO_DIR}" > /dev/null
+cd "${MAIN_REPO_DIR}"
+
+# Install required tools on alpine
+install_if_missing() {
+  # usage: install_if_missing <cmd_name> <apk_package_name>
+  CMD_NAME="$1"
+  APK_PKG="$2"
+
+  if ! command -v "$CMD_NAME" >/dev/null 2>&1; then
+    echo "Command '$CMD_NAME' not found."
+    if [ -f /etc/alpine-release ]; then
+      echo "Installing '$APK_PKG' on Alpine..."
+      apk add --no-cache "$APK_PKG"
+    else
+      echo "'$APK_PKG' not found, but this is not an Alpine image. Skipping..."
+    fi
+  fi
+}
+
+install_if_missing make make
+install_if_missing helm helm
 
 # Abort with an error exit code if
 # the lockfile was to be modified or
 # the cache folder was to be modified or
 # the checksums of the packages are not consistent
 yarn install --immutable --immutable-cache --check-cache
-
-# Add the bin directory to the PATH
-mkdir -p "${SOURCE_PATH}/bin"
-export PATH="${SOURCE_PATH}/bin:$PATH"
-
-# Install helm if it does not exist
-if [ ! -f "${SOURCE_PATH}/bin/helm" ]; then
-  VERSION="3.11.1"
-  BASE_URL="https://get.helm.sh"
-  ARCH="$(uname -m | sed 's/x86_64/amd64/')"
-  KERNEL="$(uname -s | tr '[:upper:]' '[:lower:]')"
-  wget ${BASE_URL}/helm-v${VERSION}-${KERNEL}-${ARCH}.tar.gz -O - | tar -xz -C "${SOURCE_PATH}/bin" --strip-components=1 "${KERNEL}-${ARCH}/helm"
-  chmod +x "${SOURCE_PATH}/bin/helm"
-fi
 
 # Run the helm chart unit tests
 yarn workspace @gardener-dashboard/charts run test
@@ -52,5 +58,3 @@ fi
 
 # Run tests
 make test-cov
-
-popd > /dev/null
