add enhanced user message for pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,9 @@
 # .husky/pre-commit
 set -x
+
+if ! command -v ggshield &> /dev/null; then
+  echo "Error: ggshield is not installed. Please visit https://docs.gitguardian.com/ggshield-docs/getting-started for installation instructions."
+  exit 1
+fi
+
 ggshield secret scan pre-commit "$@"
-#ToDo add check and validation and user message to check if ggshield is installed and guide the user etc.
